title: Simon Bakken-Jantasuk
url: https://blog.bakkenjantasuk.no
domain: bakkenjantasuk.no
repository: Simon-Bakken-Jantasuk/blog

author:
  name: Simon-Bakken-Jantasuk
description: >- 
  "When a student comes and asks, 'Should I become a mathematician?' the answer should be no. If you have to ask, you shouldn't even ask." - Paul Halmos

paginate: 5

minima:
  skin: dark

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

remote_theme: "jekyll/minima@1e8a445"
